<?php
declare(strict_types=1);

$config = require __DIR__ . '/config.php';
require_once __DIR__ . '/Mailer.php';

$recipient = (string) ($config['owner_email'] ?? '');

if ($recipient === '') {
    fwrite(STDERR, "owner_email is not configured.\n");
    exit(1);
}

$body = emailLayout(
    'Email configuration test',
    '<p>Your NUCLEI TECH SMTP configuration is working.</p>'
    . '<p>This test was generated by <code>backend/test_email.php</code>.</p>'
);

if (sendAppEmail($config, $recipient, 'NUCLEI TECH email test', $body)) {
    echo "Test email sent to {$recipient}.\n";
    exit(0);
}

fwrite(STDERR, "Email was not sent. Check smtp.enabled, the Gmail App Password, Composer dependencies, and PHP logs.\n");
exit(1);
